### PR TITLE
Move babel-preset-react to dev deps, simplify repository field

### PR DESCRIPTION
**Pull request by Vlad-Zhukov**
Also move unused babel-polyfill to the example where it's actually used.

### CODE REVIEW

**Comment by joshburgess** [comment]
Good call on moving babel-polyfill, but it should be in dependencies rather than devDependencies since it actually is getting imported into the global scope and used. 

And nice catch on babel-preset-react. That was an error I accidentally made when changing the babel presets last night.

**Comment by jshthornton** [comment]
@joshburgess I personally wouldn't put the pollyfill in for library code. Let the consumer be in charge of that.


Thoughts?

**Comment by joshburgess** [comment]
@jshthornton It's only used in the example repo. It doesn't get bundled into the library itself.

**Comment by Vlad-Zhukov** [comment]
@joshburgess fixed babel-polyfill.

As for the repository field, it's a [documented](https://docs.npmjs.com/files/package.json#repository) feature, and yarn also works with it.

**Comment by joshburgess** [comment]
@Vlad-Zhukov Thanks.

**Pull request merged**
